### PR TITLE
feat(graphql-jit): subscription support

### PR DESCRIPTION
**Pull request by ardatan**

### CODE REVIEW

**Review by saihaj — CHANGES_REQUESTED** [review]
we should add test for this :) similar to how we have for `execute`

**Comment by ardatan** [comment]
Yes we need to add "subscribe" to testkit

**Comment by ardatan** [comment]
Ok no subscribe is needed! It worked. PR is ready @dotansimha

**Review by dotansimha — APPROVED** [review]

**Review by saihaj — APPROVED** [review]
Awesome!

**Pull request merged**
